<a href="https://colab.research.google.com/github/Maryam-Taherzadeh/Computational-Drug-Discovery/blob/main/project-01-predict-ic50-mdm2-p53/notebooks/mdm2_part3_padel_descriptor_dataset_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🧪 Part 3: Descriptor Calculation and Dataset Preparation

**Author: Maryam Taherzadeh**

In this section, we continue the computational drug discovery pipeline by generating molecular descriptors and preparing the dataset for machine learning.

This step is inspired by the work of Chanin Nantasenamat ("Data Professor") and focuses on transforming chemical structures into numerical representations suitable for modeling.

---

### Objective

- Calculate molecular descriptors for each compound  
- Convert chemical structures into numerical features  
- Prepare a clean dataset for machine learning models  

---

###  Why this is important

Machine learning models cannot understand SMILES strings directly.

 We need to convert molecules into **numerical features (descriptors)** such as:
- Molecular Weight (MW)  
- LogP (lipophilicity)  
- Number of hydrogen bond donors  
- Number of hydrogen bond acceptors  
- Molecular fingerprints (e.g., ECFP)  

These descriptors allow the model to learn relationships between molecular structure and biological activity (pIC50).

---

###  What we will do

1. Calculate descriptors using:
   - RDKit (basic descriptors)  
   - PaDEL (advanced descriptors & fingerprints)  

2. Combine descriptors with bioactivity data (pIC50)  

3. Clean and preprocess the dataset:
   - Remove missing values  
   - Normalize features (if needed)  

4. Save the final dataset for modeling (Part 4)  

---

###  Output

- Feature matrix (X)  
- Target variable (y = pIC50)  
- Machine learning-ready dataset  

---

###  Next Step

In Part 4, we will:
- Train machine learning models (Random Forest, XGBoost)  
- Evaluate performance  
- Predict bioactivity of new compounds

## **Download PaDEL-Descriptor**

In [19]:
# Install conda in Colab
!pip install -q condacolab
import condacolab
condacolab.install()

✨🍰✨ Everything looks OK!

In [25]:
!conda create -y -n padel_env -c conda-forge python=3.10 padel

Channels:
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ done
Solving environment: / - done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.2
    latest version: 26.3.2

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local/envs/padel_env

  added / updated specs:
    - padel
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |           20_gnu          28 KB  conda-forge
    alsa-lib-1.2.15.3          |       hb03c661_0         571 KB  conda-forge
    bzip2-1.0.8                |       hda65f42_9         254 KB  conda-forge
    ca-certificates-2026.4.22  |       hbd8a1cb_0         128 KB  conda-forge
    cairo-1.18.4               |       he90730b_1         966 KB  conda-forge
    font-ttf-dejavu-sans-mono-2.37|       hab24e00_0         388 KB  conda-forge
    font-ttf-inconsolata-3.000 |       h77eed37_0          94 KB  conda-forge
    font-ttf-source-code-pro-2.038|       h77eed37_0         684 KB  conda-forge
    font-ttf-ubuntu-0.83       |       h77eed37_3         1.5 MB  conda-forge
    fontconfig-2.17.1          |       h27c8c51_0         264 KB  conda-forge
    fonts-conda-ecosystem-1    |                0           4 KB  conda-forge
    fonts-conda-forge-1        |       hc364b38_1           4 KB  conda-forge
    giflib-5.2.2               |       hd590300_0          75 KB  conda-forge
    graphite2-1.3.14           |       hecca717_2          97 KB  conda-forge
    harfbuzz-14.2.0            |       h6083320_0         2.2 MB  conda-forge
    icu-78.3                   |       h33c6efd_0        12.1 MB  conda-forge
    keyutils-1.6.3             |       hb9d3cd8_0         131 KB  conda-forge
    krb5-1.22.2                |       ha1258a1_0         1.3 MB  conda-forge
    lcms2-2.18                 |       h0c24ade_0         244 KB  conda-forge
    ld_impl_linux-64-2.45.1    |default_hbd61a6d_102         711 KB  conda-forge
    lerc-4.1.0                 |       hdb68285_0         255 KB  conda-forge
    libcups-2.3.3              |       h7a8fb5f_6         4.3 MB  conda-forge
    libdeflate-1.25            |       h17f619e_0          72 KB  conda-forge
    libedit-3.1.20250104       | pl5321h7949ede_0         132 KB  conda-forge
    libexpat-2.7.5             |       hecca717_0          75 KB  conda-forge
    libffi-3.5.2               |       h3435931_0          57 KB  conda-forge
    libfreetype-2.14.3         |       ha770c72_0           8 KB  conda-forge
    libfreetype6-2.14.3        |       h73754d4_0         376 KB  conda-forge
    libgcc-15.2.0              |      he0feb66_18        1017 KB  conda-forge
    libgcc-ng-15.2.0           |      h69a702a_18          27 KB  conda-forge
    libglib-2.86.4             |       h6548e54_1         4.2 MB  conda-forge
    libgomp-15.2.0             |      he0feb66_18         589 KB  conda-forge
    libiconv-1.18              |       h3b78370_2         772 KB  conda-forge
    libjpeg-turbo-3.1.4.1      |       hb03c661_0         619 KB  conda-forge
    liblzma-5.8.3              |       hb03c661_0         111 KB  conda-forge
    libnsl-2.0.1               |       hb9d3cd8_1          33 KB  conda-forge
    libpng-1.6.58              |       h421ea60_0         310 KB  conda-forge
    libsqlite-3.53.0           |       hf4e2dac_0         936 KB  conda-forge
    libstdcxx-15.2.0           |      h934c35e_18         5.6 MB  conda-forge
    libtiff-4.7.1              |       h9d88235_1         425 KB  conda-forge
    libuuid-2.42               |       h5347b49_0          39 KB  conda-forge
    libwebp-base-1.6.0         |       hd42ef1d_0         419 KB  conda-forge
    libxcb-1.17.0              |       h8a09558_0         387 KB  conda-forge
    libzlib-1.3.2              |       h25fd6f3_2          62 KB  conda-forge
    ncurses-6.5                |       h2d0b736_3         871 KB  conda-forge
    openjdk-25.0.2             |       ha668962_0       116.8 MB  conda-forge
    openssl-3.6.2              |       h35e630c_0         3.0 MB  conda-forge
    packaging-26.1             |     pyhc364b38_0          87 KB  conda-forge
    padel-2.21                 |  py310hff52083_5        20.0 MB  conda-forge
    pcre2-10.47                |       haa7fec5_0         1.2 MB  conda-forge
    pip-26.0.1                 |     pyh8b19718_0         1.1 MB  conda-forge
    pixman-0.46.4              |       h54a6638_1         440 KB  conda-forge
    pthread-stubs-0.4          |    hb9d3cd8_1002           8 KB  conda-forge
    python-3.10.20             |h3c07f61_0_cpython        24.3 MB  conda-forge
    python_abi-3.10            |          8_cp310           7 KB  conda-forge
    readline-8.3               |       h853b02a_0         337 KB  conda-forge
    setuptools-82.0.1          |     pyh332efcf_0         625 KB  conda-forge
    tk-8.6.13                  |noxft_h366c992_103         3.1 MB  conda-forge
    tzdata-2025c               |       hc9c84f9_1         116 KB  conda-forge
    wheel-0.47.0               |     pyhd8ed1ab_0          33 KB  conda-forge
    xorg-libice-1.1.2          |       hb9d3cd8_0          57 KB  conda-forge
    xorg-libsm-1.2.6           |       he73a12e_0          27 KB  conda-forge
    xorg-libx11-1.8.13         |       he1eb515_0         820 KB  conda-forge
    xorg-libxau-1.0.12         |       hb03c661_1          15 KB  conda-forge
    xorg-libxdmcp-1.1.5        |       hb03c661_1          20 KB  conda-forge
    xorg-libxext-1.3.7         |       hb03c661_0          49 KB  conda-forge
    xorg-libxfixes-6.0.2       |       hb03c661_0          20 KB  conda-forge
    xorg-libxi-1.8.2           |       hb9d3cd8_0          46 KB  conda-forge
    xorg-libxrandr-1.5.5       |       hb03c661_0          30 KB  conda-forge
    xorg-libxrender-0.9.12     |       hb9d3cd8_0          32 KB  conda-forge
    xorg-libxt-1.3.1           |       hb9d3cd8_0         371 KB  conda-forge
    xorg-libxtst-1.2.5         |       hb9d3cd8_3          32 KB  conda-forge
    zstd-1.5.7                 |       hb78ec9c_6         587 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       216.4 MB

The following NEW packages will be INSTALLED:

  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-20_gnu
  alsa-lib           conda-forge/linux-64::alsa-lib-1.2.15.3-hb03c661_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-hda65f42_9
  ca-certificates    conda-forge/noarch::ca-certificates-2026.4.22-hbd8a1cb_0
  cairo              conda-forge/linux-64::cairo-1.18.4-he90730b_1
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_3
  fontconfig         conda-forge/linux-64::fontconfig-2.17.1-h27c8c51_0
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-hc364b38_1
  giflib             conda-forge/linux-64::giflib-5.2.2-hd590300_0
  graphite2          conda-forge/linux-64::graphite2-1.3.14-hecca717_2
  harfbuzz           conda-forge/linux-64::harfbuzz-14.2.0-h6083320_0
  icu                conda-forge/linux-64::icu-78.3-h33c6efd_0
  keyutils           conda-forge/linux-64::keyutils-1.6.3-hb9d3cd8_0
  krb5               conda-forge/linux-64::krb5-1.22.2-ha1258a1_0
  lcms2              conda-forge/linux-64::lcms2-2.18-h0c24ade_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.45.1-default_hbd61a6d_102
  lerc               conda-forge/linux-64::lerc-4.1.0-hdb68285_0
  libcups            conda-forge/linux-64::libcups-2.3.3-h7a8fb5f_6
  libdeflate         conda-forge/linux-64::libdeflate-1.25-h17f619e_0
  libedit            conda-forge/linux-64::libedit-3.1.20250104-pl5321h7949ede_0
  libexpat           conda-forge/linux-64::libexpat-2.7.5-hecca717_0
  libffi             conda-forge/linux-64::libffi-3.5.2-h3435931_0
  libfreetype        conda-forge/linux-64::libfreetype-2.14.3-ha770c72_0
  libfreetype6       conda-forge/linux-64::libfreetype6-2.14.3-h73754d4_0
  libgcc             conda-forge/linux-64::libgcc-15.2.0-he0feb66_18
  libgcc-ng          conda-forge/linux-64::libgcc-ng-15.2.0-h69a702a_18
  libglib            conda-forge/linux-64::libglib-2.86.4-h6548e54_1
  libgomp            conda-forge/linux-64::libgomp-15.2.0-he0feb66_18
  libiconv           conda-forge/linux-64::libiconv-1.18-h3b78370_2
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.1.4.1-hb03c661_0
  liblzma            conda-forge/linux-64::liblzma-5.8.3-hb03c661_0
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hb9d3cd8_1
  libpng             conda-forge/linux-64::libpng-1.6.58-h421ea60_0
  libsqlite          conda-forge/linux-64::libsqlite-3.53.0-hf4e2dac_0
  libstdcxx          conda-forge/linux-64::libstdcxx-15.2.0-h934c35e_18
  libtiff            conda-forge/linux-64::libtiff-4.7.1-h9d88235_1
  libuuid            conda-forge/linux-64::libuuid-2.42-h5347b49_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.6.0-hd42ef1d_0
  libxcb             conda-forge/linux-64::libxcb-1.17.0-h8a09558_0
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1
  libzlib            conda-forge/linux-64::libzlib-1.3.2-h25fd6f3_2
  ncurses            conda-forge/linux-64::ncurses-6.5-h2d0b736_3
  openjdk            conda-forge/linux-64::openjdk-25.0.2-ha668962_0
  openssl            conda-forge/linux-64::openssl-3.6.2-h35e630c_0
  packaging          conda-forge/noarch::packaging-26.1-pyhc364b38_0
  padel              conda-forge/linux-64::padel-2.21-py310hff52083_5
  pcre2              conda-forge/linux-64::pcre2-10.47-haa7fec5_0
  pip                conda-forge/noarch::pip-26.0.1-pyh8b19718_0
  pixman             conda-forge/linux-64::pixman-0.46.4-h54a6638_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-hb9d3cd8_1002
  python             conda-forge/linux-64::python-3.10.20-h3c07f61_0_cpython
  python_abi         conda-forge/noarch::python_abi-3.10-8_cp310
  readline           conda-forge/linux-64::readline-8.3-h853b02a_0
  setuptools         conda-forge/noarch::setuptools-82.0.1-pyh332efcf_0
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h366c992_103
  tzdata             conda-forge/noarch::tzdata-2025c-hc9c84f9_1
  wheel              conda-forge/noarch::wheel-0.47.0-pyhd8ed1ab_0
  xorg-libice        conda-forge/linux-64::xorg-libice-1.1.2-hb9d3cd8_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.6-he73a12e_0
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.13-he1eb515_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.12-hb03c661_1
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.5-hb03c661_1
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.7-hb03c661_0
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-6.0.2-hb03c661_0
  xorg-libxi         conda-forge/linux-64::xorg-libxi-1.8.2-hb9d3cd8_0
  xorg-libxrandr     conda-forge/linux-64::xorg-libxrandr-1.5.5-hb03c661_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.12-hb9d3cd8_0
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.3.1-hb9d3cd8_0
  xorg-libxtst       conda-forge/linux-64::xorg-libxtst-1.2.5-hb9d3cd8_3
  zstd               conda-forge/linux-64::zstd-1.5.7-hb78ec9c_6



Downloading and Extracting Packages:
openjdk-25.0.2       | 116.8 MB  | :   0% 0/1 [00:00<?, ?it/s]
python-3.10.20       | 24.3 MB   | :   0% 0/1 [00:00<?, ?it/s]

padel-2.21           | 20.0 MB   | :   0% 0/1 [00:00<?, ?it/s]


icu-78.3             | 12.1 MB   | :   0% 0/1 [00:00<?, ?it/s]



libstdcxx-15.2.0     | 5.6 MB    | :   0% 0/1 [00:00<?, ?it/s]




libcups-2.3.3        | 4.3 MB    | :   0% 0/1 [00:00<?, ?it/s]





libglib-2.86.4       | 4.2 MB    | :   0% 0/1 [00:00<?, ?it/s]






tk-8.6.13            | 3.1 MB    | :   0% 0/1 [00:00<?, ?it/s]







openssl-3.6.2        | 3.0 MB    | :   0% 0/1 [00:00<?, ?it/s]








harfbuzz-14.2.0      | 2.2 MB    | :   0% 0/1 [00:00<?, ?it/s]









font-ttf-ubuntu-0.83 | 1.5 MB    | :   0% 0/1 [00:00<?, ?it/s]










krb5-1.22.2          | 1.3 MB    | :   0% 0/1 [00:00<?, ?it/s]











pcre2-10.47          | 1.2 MB    | :   0% 0/1 [00:00<?, ?it/s]












pip-26.0.1           | 1.1 MB    | :   0% 0/1 [00:00<?, ?it/s]













libgcc-15.2.0        | 1017 KB   | :   0% 0/1 [00:00<?, ?it/s]














cairo-1.18.4         | 966 KB    | :   0% 0/1 [00:00<?, ?it/s]















libsqlite-3.53.0     | 936 KB    | :   0% 0/1 [00:00<?, ?it/s]
















ncurses-6.5          | 871 KB    | :   0% 0/1 [00:00<?, ?it/s]

















xorg-libx11-1.8.13   | 820 KB    | :   0% 0/1 [00:00<?, ?it/s]


















openjdk-25.0.2       | 116.8 MB  | :   0% 0.00013378512924232226/1 [00:00<12:34, 754.33s/it]
python-3.10.20       | 24.3 MB   | :   0% 0.0006436370016163995/1 [00:00<02:36, 156.69s/it]


icu-78.3             | 12.1 MB   | :   0% 0.002575401909434791/1 [00:00<00:38, 38.85s/it]



libstdcxx-15.2.0     | 5.6 MB    | :   1% 0.013997843593919004/1 [00:00<00:07,  7.35s/it]

openjdk-25.0.2       | 116.8 MB  | :   2% 0.022342116583467814/1 [00:00<00:07,  7.66s/it]
python-3.10.20       | 24.3 MB   | :  10% 0.1023382832570075/1 [00:00<00:01,  1.67s/it]


icu-78.3             | 12.1 MB   | :  20% 0.2008813489359137/1 [00:00<00:00,  1.18it/s]



libstdcxx-15.2.0     | 5.6 MB    | :  56% 0.5571141750379763/1 [00:00<00:00,  3.21it/s]

openjdk-25.0.2       | 116.8 MB  | :   6% 0.058062746091167856/1 [00:00<00:04,  4.29s/it]
python-3.10.20       | 24.3 MB   | :  27% 0.27225845168373697/1 [00:00<00:00,  1.09it/s]


icu-78.3             | 12.1 MB   | :  56% 0.5640130181662192/1 [00:00<00:00,  2.29it/s]



libstdcxx-15.2.0     | 5.6 MB    | : 100% 1.0/1 [00:00<00:00,  3.53it/s]



libstdcxx-15.2.0     | 5.6 MB    | : 100% 1.0/1 [00:00<00:00,  3.53it/s]

padel-2.21           | 20.0 MB   | :  31% 0.31483781261418564/1 [00:00<00:00,  1.19it/s]




openjdk-25.0.2       | 116.8 MB  | :   9% 0.09217795404796003/1 [00:00<00:03,  3.63s/it]
python-3.10.20       | 24.3 MB   | :  38% 0.38296401596175766/1 [00:00<00:00,  1.10it/s]


icu-78.3             | 12.1 MB   | :  89% 0.8898013597097203/1 [00:00<00:00,  2.67it/s]

padel-2.21           | 20.0 MB   | :  45% 0.4471950024942786/1 [00:00<00:00,  1.24it/s]




openjdk-25.0.2       | 116.8 MB  | :  12% 0.12013904605960538/1 [00:00<00:03,  3.61s/it]
python-3.10.20       | 24.3 MB   | :  53% 0.5277823413254475/1 [00:00<00:00,  1.22it/s]

padel-2.21           | 20.0 MB   | :  62% 0.618711124291559/1 [00:00<00:00,  1.40it/s]




libcups-2.3.3        | 4.3 MB    | : 100% 1.0/1 [00:00<00:00,  2.00it/s]





libglib-2.86.4       | 4.2 MB    | :   0% 0.003724736007289425/1 [00:00<02:30, 150.73s/it]
openjdk-25.0.2       | 116.8 MB  | :  15% 0.14783256781276607/1 [00:00<00:03,  3.88s/it]


icu-78.3             | 12.1 MB   | : 100% 1.0/1 [00:00<00:00,  2.67it/s]

padel-2.21           | 20.0 MB   | :  78% 0.7776963878753392/1 [00:00<00:00,  1.46it/s]






tk-8.6.13            | 3.1 MB    | :   0% 0.004963049755300806/1 [00:00<02:11, 132.41s/it]





openjdk-25.0.2       | 116.8 MB  | :  18% 0.1756598746951691/1 [00:00<00:03,  3.79s/it]
python-3.10.20       | 24.3 MB   | :  78% 0.7762262239493777/1 [00:00<00:00,  1.14it/s]

padel-2.21           | 20.0 MB   | :  94% 0.9358984728207758/1 [00:00<00:00,  1.50it/s]






tk-8.6.13            | 3.1 MB    | :  95% 0.9529055530177548/1 [00:00<00:00,  1.69it/s]





libglib-2.86.4       | 4.2 MB    | : 100% 1.0/1 [00:00<00:00,  1.71it/s]





libglib-2.86.4       | 4.2 MB    | : 100% 1.0/1 [00:00<00:00,  1.71it/s]






tk-8.6.13            | 3.1 MB    | : 100% 1.0/1 [00:00<00:00,  1.69it/s]
openjdk-25.0.2       | 116.8 MB  | :  20% 0.20228311541439123/1 [00:00<00:03,  4.11s/it]







openssl-3.6.2        | 3.0 MB    | :   1% 0.005173188460480711/1 [00:00<02:43, 164.78s/it]








harfbuzz-14.2.0      | 2.2 MB    | :   1% 0.007020914904403027/1 [00:00<02:01, 122.72s/it]

openjdk-25.0.2       | 116.8 MB  | :  23% 0.23198341410618678/1 [00:00<00:02,  3.87s/it]









font-ttf-ubuntu-0.83 | 1.5 MB    | :   1% 0.010110434778315882/1 [00:00<01:33, 94.62s/it]








harfbuzz-14.2.0      | 2.2 MB    | : 100% 1.0/1 [00:00<00:00, 122.72s/it]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  1.39it/s]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  1.39it/s]



libstdcxx-15.2.0     | 5.6 MB    | : 100% 1.0/1 [00:00<00:00,  3.53it/s]










krb5-1.22.2          | 1.3 MB    | :   1% 0.011814844995060322/1 [00:01<01:23, 84.74s/it]











pcre2-10.47          | 1.2 MB    | :   1% 0.013402253286554146/1 [00:01<01:15, 76.05s/it]









openjdk-25.0.2       | 116.8 MB  | :  26% 0.2608810020225284/1 [00:01<00:02,  3.77s/it]










krb5-1.22.2          | 1.3 MB    | : 100% 1.0/1 [00:01<00:00, 84.74s/it]




libcups-2.3.3        | 4.3 MB    | : 100% 1.0/1 [00:01<00:00,  2.00it/s]











pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:01<00:00, 76.05s/it]
python-3.10.20       | 24.3 MB   | : 100% 1.0/1 [00:01<00:00,  1.13it/s]













libgcc-15.2.0        | 1017 KB   | :   2% 0.01572680814138769/1 [00:01<01:07, 69.00s/it]














cairo-1.18.4         | 966 KB    | :   2% 0.01655762323726597/1 [00:01<01:04, 65.89s/it]












pip-26.0.1           | 1.1 MB    | :   1% 0.013863715211670432/1 [00:01<01:18, 80.11s/it]















libsqlite-3.53.0     | 936 KB    | :   2% 0.017086886148609187/1 [00:01<01:04, 65.45s/it]














cairo-1.18.4         | 966 KB    | : 100% 1.0/1 [00:01<00:00, 65.89s/it]













openjdk-25.0.2       | 116.8 MB  | :  29% 0.28777181300023513/1 [00:01<00:02,  3.87s/it]
















ncurses-6.5          | 871 KB    | :   2% 0.018375108367605347/1 [00:01<01:01, 62.99s/it]















libsqlite-3.53.0     | 936 KB    | : 100% 1.0/1 [00:01<00:00, 65.45s/it]












pip-26.0.1           | 1.1 MB    | : 100% 1.0/1 [00:01<00:00, 80.11s/it]
















ncurses-6.5          | 871 KB    | : 100% 1.0/1 [00:01<00:00, 62.99s/it]

















xorg-libx11-1.8.13   | 820 KB    | :   2% 0.019512845798021084/1 [00:01<00:59, 61.01s/it]

















xorg-libx11-1.8.13   | 820 KB    | : 100% 1.0/1 [00:01<00:00, 61.01s/it]


















 ... (more hidden) ...


















openjdk-25.0.2       | 116.8 MB  | :  69% 0.6919366884412906/1 [00:02<00:00,  3.19s/it]


icu-78.3             | 12.1 MB   | : 100% 1.0/1 [00:02<00:00,  2.67it/s]





openjdk-25.0.2       | 116.8 MB  | :  96% 0.9637880710616894/1 [00:02<00:00,  1.82s/it]






openjdk-25.0.2       | 116.8 MB  | : 100% 1.0/1 [00:03<00:00,  1.82s/it]








harfbuzz-14.2.0      | 2.2 MB    | : 100% 1.0/1 [00:03<00:00,  2.87s/it]








harfbuzz-14.2.0      | 2.2 MB    | : 100% 1.0/1 [00:03<00:00,  2.87s/it]







openssl-3.6.2        | 3.0 MB    | : 100% 1.0/1 [00:03<00:00,  1.39it/s]









font-ttf-ubuntu-0.83 | 1.5 MB    | : 100% 1.0/1 [00:03<00:00,  3.09s/it]









font-ttf-ubuntu-0.83 | 1.5 MB    | : 100% 1.0/1 [00:03<00:00,  3.09s/it]










krb5-1.22.2          | 1.3 MB    | : 100% 1.0/1 [00:03<00:00,  3.25s/it]










krb5-1.22.2          | 1.3 MB    | : 100% 1.0/1 [00:03<00:00,  3.25s/it]











pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:03<00:00,  3.47s/it]











pcre2-10.47          | 1.2 MB    | : 100% 1.0/1 [00:03<00:00,  3.47s/it]
python-3.10.20       | 24.3 MB   | : 100% 1.0/1 [00:05<00:00,  1.13it/s]















In [26]:
!conda run -n padel_env bash -lc 'find $CONDA_PREFIX -name "*PaDEL*.jar"'

/usr/local/envs/padel_env/PaDEL-Descriptor.jar
/usr/local/envs/padel_env/lib/libPaDEL.jar
/usr/local/envs/padel_env/lib/libPaDEL-Jobs.jar
/usr/local/envs/padel_env/lib/libPaDEL-Descriptor.jar

In [27]:
!which padel
!which padeldescriptor
!conda list | grep padel
# !padel -h
!find /usr/local -name "*PaDEL*.jar"

/usr/local/pkgs/padel-2.21-py310hff52083_5/PaDEL-Descriptor.jar
/usr/local/pkgs/padel-2.21-py310hff52083_5/lib/libPaDEL.jar
/usr/local/pkgs/padel-2.21-py310hff52083_5/lib/libPaDEL-Jobs.jar
/usr/local/pkgs/padel-2.21-py310hff52083_5/lib/libPaDEL-Descriptor.jar
/usr/local/envs/padel_env/PaDEL-Descriptor.jar
/usr/local/envs/padel_env/lib/libPaDEL.jar
/usr/local/envs/padel_env/lib/libPaDEL-Jobs.jar
/usr/local/envs/padel_env/lib/libPaDEL-Descriptor.jar

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [28]:

from google.colab import files
uploaded = files.upload()

Saving my_bioactivity_data.csv to my_bioactivity_data (1).csv

In [29]:
import pandas as pd

In [30]:
df3 = pd.read_csv('my_bioactivity_data.csv')

In [31]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,mol,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,CHEMBL178578,O=C(O)[C@H](c1ccccc1)N1C(=O)c2cc(I)ccc2NC(=O)[...,intermediate,<rdkit.Chem.rdchem.Mol object at 0x7e8f8cc297e0>,580.300,5.27150,2,3,5.769551
1,CHEMBL361103,O=C(O)[C@H](c1ccc(Cl)cc1)N1C(=O)c2cc(I)ccc2NC(...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8f8cc299a0>,581.193,5.55950,2,3,6.698970
2,CHEMBL182051,C[C@H](c1ccc(Cl)cc1)N(C(=O)/C=C/c1ccccc1)[C@H]...,inactive,<rdkit.Chem.rdchem.Mol object at 0x7e8f8cc29a10>,453.369,5.82300,1,2,4.522879
3,CHEMBL360540,C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2)N(CCCC...,inactive,<rdkit.Chem.rdchem.Mol object at 0x7e8f8cc29a80>,551.470,6.76250,1,3,4.886057
4,CHEMBL427316,C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2Br)N(CC...,intermediate,<rdkit.Chem.rdchem.Mol object at 0x7e8f8cc29af0>,630.366,7.52500,1,3,5.443697
...,...,...,...,...,...,...,...,...,...
5787,CHEMBL6014971,COc1ncc(-c2nc3c(n2C(C)C)[C@H](c2ccc(Cl)cc2)N(c...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8fb4151380>,568.417,5.72350,0,8,9.619789
5788,CHEMBL5805098,COc1ncc(-c2nc3c(n2C(C)C)[C@H](c2ccc(Cl)cc2)N(c...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8fb41513f0>,547.999,5.37852,0,8,9.161151
5789,CHEMBL6045300,COc1ncc(-c2nc3c(n2C(C)C)[C@@H](c2ccc(Cl)cc2)N(...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8fb4151460>,565.421,5.03750,0,8,8.543634
5790,CHEMBL6055628,COc1ncc(-c2nc3c(n2C(C)C)[C@@H](c2ccc(Cl)cc2)N(...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8fb41514d0>,564.433,5.64250,0,7,9.602060
5791,CHEMBL5784605,COc1ncc(-c2nc3c(n2C(C)C)C(c2ccc(Cl)cc2)N(c2cc(...,active,<rdkit.Chem.rdchem.Mol object at 0x7e8fb4151540>,564.433,5.87110,1,7,8.958607

In [32]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [33]:
! cat molecule.smi | head -5

O=C(O)[C@H](c1ccccc1)N1C(=O)c2cc(I)ccc2NC(=O)[C@@H]1c1ccc(C(F)(F)F)cc1	CHEMBL178578
O=C(O)[C@H](c1ccc(Cl)cc1)N1C(=O)c2cc(I)ccc2NC(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL361103
C[C@H](c1ccc(Cl)cc1)N(C(=O)/C=C/c1ccccc1)[C@H](C(N)=O)c1ccc(Cl)cc1	CHEMBL182051
C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2)N(CCCCC(=O)O)C(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL360540
C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2Br)N(CCCCC(=O)O)C(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL427316

In [34]:
! cat molecule.smi | wc -l

5792

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [38]:
!java -jar /usr/local/envs/padel_env/PaDEL-Descriptor.jar \
 -removesalt \
 -standardizenitro \
 -fingerprints \
 -dir ./ \
 -file descriptors_output.csv

Streaming output truncated to the last 5000 lines.
Processing CHEMBL3318780 in molecule.smi (794/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318781 in molecule.smi (795/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318782 in molecule.smi (796/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318783 in molecule.smi (797/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318784 in molecule.smi (798/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318785 in molecule.smi (799/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318786 in molecule.smi (800/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3318787 in molecule.smi (801/5792). Average speed: 0.16 s/mol.
Processing CHEMBL2398246 in molecule.smi (802/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402515 in molecule.smi (803/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402516 in molecule.smi (804/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402517 in molecule.smi (805/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402518 in molecule.smi (806/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402520 in molecule.smi (808/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402519 in molecule.smi (807/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3402521 in molecule.smi (809/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407555 in molecule.smi (810/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407554 in molecule.smi (811/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3125537 in molecule.smi (812/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3125702 in molecule.smi (813/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407574 in molecule.smi (814/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407573 in molecule.smi (815/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407572 in molecule.smi (816/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407571 in molecule.smi (817/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407570 in molecule.smi (818/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407569 in molecule.smi (819/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407568 in molecule.smi (820/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407566 in molecule.smi (822/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407567 in molecule.smi (821/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407565 in molecule.smi (823/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407564 in molecule.smi (824/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407563 in molecule.smi (825/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407562 in molecule.smi (826/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407561 in molecule.smi (827/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407560 in molecule.smi (828/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407559 in molecule.smi (829/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407558 in molecule.smi (830/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407557 in molecule.smi (831/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407556 in molecule.smi (832/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3236364 in molecule.smi (833/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407555 in molecule.smi (834/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407554 in molecule.smi (835/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3125537 in molecule.smi (836/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407576 in molecule.smi (838/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3125702 in molecule.smi (837/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407575 in molecule.smi (839/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407569 in molecule.smi (840/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407558 in molecule.smi (841/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3407557 in molecule.smi (842/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3125537 in molecule.smi (843/5792). Average speed: 0.16 s/mol.
Processing CHEMBL407632 in molecule.smi (844/5792). Average speed: 0.16 s/mol.
Processing CHEMBL191334 in molecule.smi (845/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627749 in molecule.smi (846/5792). Average speed: 0.16 s/mol.
Processing CHEMBL191334 in molecule.smi (847/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627750 in molecule.smi (848/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627748 in molecule.smi (849/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627747 in molecule.smi (850/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627746 in molecule.smi (851/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627744 in molecule.smi (852/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3627743 in molecule.smi (853/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687236 in molecule.smi (854/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653217 in molecule.smi (856/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691713 in molecule.smi (855/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653290 in molecule.smi (857/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657058 in molecule.smi (858/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653211 in molecule.smi (859/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691748 in molecule.smi (860/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657098 in molecule.smi (861/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691706 in molecule.smi (862/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653225 in molecule.smi (864/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683129 in molecule.smi (863/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3639521 in molecule.smi (866/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691722 in molecule.smi (865/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653295 in molecule.smi (867/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687295 in molecule.smi (868/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687237 in molecule.smi (869/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687269 in molecule.smi (870/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683172 in molecule.smi (871/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657023 in molecule.smi (872/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691710 in molecule.smi (873/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691772 in molecule.smi (874/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657105 in molecule.smi (875/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691705 in molecule.smi (876/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691787 in molecule.smi (877/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653238 in molecule.smi (878/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657110 in molecule.smi (879/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653192 in molecule.smi (880/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687245 in molecule.smi (881/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653272 in molecule.smi (882/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3656993 in molecule.smi (883/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657080 in molecule.smi (884/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687316 in molecule.smi (885/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683138 in molecule.smi (886/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653256 in molecule.smi (887/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683158 in molecule.smi (888/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691785 in molecule.smi (889/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653223 in molecule.smi (890/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657060 in molecule.smi (891/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657124 in molecule.smi (892/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691791 in molecule.smi (893/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657033 in molecule.smi (894/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691781 in molecule.smi (895/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683163 in molecule.smi (896/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653177 in molecule.smi (897/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653169 in molecule.smi (898/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657109 in molecule.smi (899/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683110 in molecule.smi (900/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687230 in molecule.smi (901/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657053 in molecule.smi (902/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657095 in molecule.smi (904/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691721 in molecule.smi (903/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3639820 in molecule.smi (905/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3656997 in molecule.smi (906/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3601323 in molecule.smi (907/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653249 in molecule.smi (908/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687299 in molecule.smi (909/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3656988 in molecule.smi (910/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691720 in molecule.smi (911/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657091 in molecule.smi (912/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687294 in molecule.smi (913/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657029 in molecule.smi (914/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691752 in molecule.smi (915/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653172 in molecule.smi (916/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3601322 in molecule.smi (917/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657028 in molecule.smi (918/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687258 in molecule.smi (919/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687305 in molecule.smi (920/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653201 in molecule.smi (921/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691695 in molecule.smi (922/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687232 in molecule.smi (923/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683144 in molecule.smi (924/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687311 in molecule.smi (925/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657092 in molecule.smi (927/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687227 in molecule.smi (926/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691758 in molecule.smi (928/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653165 in molecule.smi (929/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653261 in molecule.smi (930/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657046 in molecule.smi (931/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683128 in molecule.smi (932/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3601319 in molecule.smi (933/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691719 in molecule.smi (934/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657099 in molecule.smi (935/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653240 in molecule.smi (936/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687238 in molecule.smi (938/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650074 in molecule.smi (937/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650065 in molecule.smi (939/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657094 in molecule.smi (940/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687263 in molecule.smi (941/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691716 in molecule.smi (943/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657078 in molecule.smi (942/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657112 in molecule.smi (945/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3601320 in molecule.smi (944/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653226 in molecule.smi (946/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653206 in molecule.smi (947/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683106 in molecule.smi (948/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683160 in molecule.smi (949/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683155 in molecule.smi (950/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683183 in molecule.smi (951/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3656978 in molecule.smi (952/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653259 in molecule.smi (953/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657107 in molecule.smi (954/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687291 in molecule.smi (955/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657021 in molecule.smi (956/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691786 in molecule.smi (958/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691699 in molecule.smi (957/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650055 in molecule.smi (959/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683121 in molecule.smi (960/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657127 in molecule.smi (961/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687239 in molecule.smi (962/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687307 in molecule.smi (963/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687244 in molecule.smi (964/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650076 in molecule.smi (965/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683139 in molecule.smi (966/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657008 in molecule.smi (967/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691711 in molecule.smi (968/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3604660 in molecule.smi (969/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653260 in molecule.smi (971/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650059 in molecule.smi (970/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653294 in molecule.smi (972/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691704 in molecule.smi (973/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691721 in molecule.smi (974/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657093 in molecule.smi (975/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691718 in molecule.smi (976/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687241 in molecule.smi (977/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657043 in molecule.smi (978/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691747 in molecule.smi (979/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687262 in molecule.smi (980/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687259 in molecule.smi (981/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657005 in molecule.smi (982/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653308 in molecule.smi (983/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653160 in molecule.smi (984/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691737 in molecule.smi (985/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687290 in molecule.smi (986/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657010 in molecule.smi (987/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3656991 in molecule.smi (988/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683157 in molecule.smi (989/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683150 in molecule.smi (990/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657059 in molecule.smi (991/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653196 in molecule.smi (992/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687318 in molecule.smi (993/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687282 in molecule.smi (994/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691770 in molecule.smi (995/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691760 in molecule.smi (996/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691773 in molecule.smi (997/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653292 in molecule.smi (998/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653224 in molecule.smi (999/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657068 in molecule.smi (1000/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650054 in molecule.smi (1001/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687260 in molecule.smi (1002/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653167 in molecule.smi (1003/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657044 in molecule.smi (1004/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687256 in molecule.smi (1005/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657082 in molecule.smi (1006/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683184 in molecule.smi (1007/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657039 in molecule.smi (1008/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653283 in molecule.smi (1009/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691735 in molecule.smi (1010/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687280 in molecule.smi (1012/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683114 in molecule.smi (1011/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3683105 in molecule.smi (1013/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657014 in molecule.smi (1014/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653279 in molecule.smi (1015/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653203 in molecule.smi (1017/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691700 in molecule.smi (1016/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653188 in molecule.smi (1019/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3650071 in molecule.smi (1018/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691708 in molecule.smi (1020/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657056 in molecule.smi (1021/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3653200 in molecule.smi (1022/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687247 in molecule.smi (1023/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3683143 in molecule.smi (1024/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3691728 in molecule.smi (1025/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3657126 in molecule.smi (1026/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3687314 in molecule.smi (1027/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3656986 in molecule.smi (1028/5792). Average speed: 0.16 s/mol.
Processing CHEMBL3657064 in molecule.smi (1029/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3683151 in molecule.smi (1030/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3657009 in molecule.smi (1031/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3683176 in molecule.smi (1032/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3683125 in molecule.smi (1033/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3657057 in molecule.smi (1034/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3691729 in molecule.smi (1035/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3683140 in molecule.smi (1036/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3653265 in molecule.smi (1037/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3691736 in molecule.smi (1038/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3657089 in molecule.smi (1039/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3653273 in molecule.smi (1040/5792). Average speed: 0.15 s/mol.
Processing CHEMBL3657073 in molecule.smi (1041/5792). Average speed: 0.15 s/mol.

In [42]:
import pandas as pd

df_padel = pd.read_csv('descriptors_output.csv')
df_padel.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL178578,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL361103,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL182051,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL360540,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL427316,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Warning: Total number of columns (882) exceeds max_columns (20) limiting to first (20) columns.

In [43]:
df_padel.shape

(5792, 882)

In [44]:
! cat molecule.smi | head -5

O=C(O)[C@H](c1ccccc1)N1C(=O)c2cc(I)ccc2NC(=O)[C@@H]1c1ccc(C(F)(F)F)cc1	CHEMBL178578
O=C(O)[C@H](c1ccc(Cl)cc1)N1C(=O)c2cc(I)ccc2NC(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL361103
C[C@H](c1ccc(Cl)cc1)N(C(=O)/C=C/c1ccccc1)[C@H](C(N)=O)c1ccc(Cl)cc1	CHEMBL182051
C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2)N(CCCCC(=O)O)C(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL360540
C[C@H](c1ccc(Cl)cc1)N1C(=O)C=C(c2ccccc2Br)N(CCCCC(=O)O)C(=O)[C@@H]1c1ccc(Cl)cc1	CHEMBL427316

In [45]:
! cat molecule.smi | wc -l

5792

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [46]:
df3_X = pd.read_csv('descriptors_output.csv')

In [47]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL178578,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL361103,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL182051,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL360540,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL427316,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5787,CHEMBL5805098,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5788,CHEMBL6014971,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5789,CHEMBL6045300,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5790,CHEMBL6055628,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5791,CHEMBL5784605,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5787,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5788,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5789,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5790,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5791,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [49]:
df3_Y = df3['pIC50']
df3_Y

0       5.769551
1       6.698970
2       4.522879
3       4.886057
4       5.443697
          ...
5787    9.619789
5788    9.161151
5789    8.543634
5790    9.602060
5791    8.958607
Name: pIC50, Length: 5792, dtype: float64

## **Combining X and Y variable**

In [50]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.769551
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.698970
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.522879
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.886057
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.443697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5787,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.619789
5788,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.161151
5789,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8.543634
5790,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.602060
5791,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8.958607

In [52]:
dataset3.to_csv('mdm2_07_padel_descriptors_pIC50.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**